# Generated by Django 6.1 on 2026-09-04 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='DtaNas',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
    ]
